# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'AuToFF-Manual'
copyright = '2022, WangC'
author = '王聪，王兆敏 等'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx_panels",
    "sphinx_copybutton",
    "sphinx_togglebutton",
    'sphinxcontrib.bibtex',
    'sphinx.ext.mathjax'
]

bibtex_bibfiles = ['refs.bib']

bibtex_default_style = 'mystyle'

mathjax3_config = {
    "tex": {"extensions": ["mhchem.js"]}
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh'

numfig = True

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

latex_engine = 'xelatex'

latex_elements = {
    'preamble': r'''
\usepackage{cite}
\usepackage{longtable}
\usepackage[version=4]{mhchem}
\hypersetup{unicode=true}
\usepackage{ctex}
\parindent 2em
\definecolor{VerbatimColor}{rgb}{0.95,0.95,0.95}
\renewcommand\familydefault{\ttdefault}
\renewcommand\CJKfamilydefault{\CJKrmdefault}
\addto\captionsenglish{\renewcommand{\chaptername}{}}
'''
}

pdf_documents = [
    ('index'),
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_logo = './image/AuToFF_logo1.png'

html_context = {
    "display_github": True, # Integrate GitHub
    "github_user": "LZ0211", # Username
    "github_repo": "AuToFF-Manual", # Repo name
    "github_version": "master", # Version
    #"conf_py_path": "/source/", # Path in the checkout to the docs root
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# pygments_style = 'colorful'


import pybtex.plugin
from pybtex.style.formatting.unsrt import Style as UnsrtStyle
from pybtex.style.template import field

class MyStyle(UnsrtStyle):
    def format_title(self, e, which_field):
        return field(which_field)

pybtex.plugin.register_plugin('pybtex.style.formatting', 'mystyle', MyStyle)
